---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r loading_and_preprocessing_the_data, echo = TRUE}
InstallAndLoadRequiredPackages <- function() {
  # Load the required packages.
  if (!require('pacman')) {
    install.packages('pacman')
  }
  pacman::p_load(chron, data.table, dtplyr, tidyverse)
}

InstallAndLoadRequiredPackages()

activity.monitoring.data <- read_csv('activity.zip')
```

## What is the total number of steps taken per day?
```{r total_steps_per_day, echo = TRUE}
activity.monitoring.data.total.steps.per.day <-  activity.monitoring.data %>%
  group_by(date) %>%
  summarise(total.steps = sum(steps, na.rm = TRUE)) 

activity.monitoring.data.total.steps.per.day %>%
  ggplot(aes(date, total.steps)) + geom_col() +
  ggtitle('Activity Monitoring Data, Total Steps per Date') +
  ylab('total steps taken')
```

## What is mean number of steps taken per day?
```{r mean_steps_per_day, echo = TRUE}
activity.monitoring.data.mean.steps.per.day <- mean(activity.monitoring.data.total.steps.per.day$total.steps, 
                                                    na.rm = TRUE)

print(paste('Mean number of steps taken per day:', as.integer(activity.monitoring.data.mean.steps.per.day)))
```

## What is median total number of steps taken per day?
```{r median_total_steps_per_day, echo = TRUE}
activity.monitoring.data.median.steps.per.day <- median(activity.monitoring.data.total.steps.per.day$total.steps, 
                                                    na.rm = TRUE)

print(paste('Median number of steps taken per day:', as.integer(activity.monitoring.data.median.steps.per.day)))
```


## What is the average daily activity pattern?
```{r average_activity_daily_pattern, echo = TRUE}
average.steps.by.interval <- activity.monitoring.data %>%
  group_by(interval) %>%
  summarise(mean.steps = mean(steps, na.rm = TRUE))

average.steps.by.interval %>%
  ggplot(aes(interval, mean.steps)) +
  geom_line() +
  ggtitle('Activity Monitoring Data, Average Steps per 5-minute Interval') +
  xlab('5-minute interval') +
  ylab('average steps') +
  geom_point(data = subset(average.steps.by.interval, mean.steps == max(mean.steps))) +
  geom_text(aes(label = ifelse(mean.steps == max(mean.steps), paste('Interval with max steps: ', interval), '')), 
            hjust = 1, vjust = 0)
```

## Inputting missing values
```{r inputting_missing_values, echo = TRUE}
print(paste('Total number of missing values in the dataset:', sum(is.na(activity.monitoring.data$steps))))

###

activity.monitoring.data.na.filled <- activity.monitoring.data %>%
  mutate(steps = ifelse(is.na(steps), average.steps.by.interval$mean.steps, steps))

###

activity.monitoring.data.na.filled.total.steps.per.day <-  activity.monitoring.data.na.filled %>%
  group_by(date) %>%
  summarise(total.steps = sum(steps))

activity.monitoring.data.na.filled.mean.steps.per.day <- 
  mean(activity.monitoring.data.na.filled.total.steps.per.day$total.steps)

activity.monitoring.data.na.filled.median.steps.per.day <- 
  median(activity.monitoring.data.na.filled.total.steps.per.day$total.steps)

### 

bind_rows('ORIGINAL' = activity.monitoring.data.total.steps.per.day,
          'NA-FILLED (with Interval Mean)' = activity.monitoring.data.na.filled.total.steps.per.day,
          .id = 'from.NA.filled') %>%
  ggplot(aes(date, total.steps, fill = from.NA.filled)) +
  geom_col(position = "dodge") +
  ggtitle('Activity Monitoring Data, Original and NA-Filled comparison') +
  ylab('total steps taken')

print(paste('Mean number of steps taken per day, ORIGINAL:', 
            as.integer(activity.monitoring.data.mean.steps.per.day)))
print(paste('Mean number of steps taken per day, NA-FILLED:', 
            as.integer(activity.monitoring.data.na.filled.mean.steps.per.day)))
print(paste('Median number of steps taken per day, ORIGINAL:', 
            as.integer(activity.monitoring.data.median.steps.per.day)))
print(paste('Median number of steps taken per day, NA-FILLED:', 
            as.integer(activity.monitoring.data.na.filled.median.steps.per.day)))

```


## Are there differences in activity patterns between weekdays and weekends?
```{r weekdays_and_weekends, echo = TRUE}
activity.monitoring.data.na.filled %>%
  mutate(weekend = ifelse(is.weekend(date), TRUE, FALSE)) %>%
  group_by(interval, weekend) %>%
  summarise(mean.steps = mean(steps)) %>%
  ggplot(aes(interval, mean.steps, color = weekend)) + 
  geom_line() +
  ggtitle('Activity Monitoring Data, Average Steps per 5-minute Interval') +
  xlab('5-minute interval') +
  ylab('average steps')
```
